observatorium/api

- internal/server/instrumentation.go
- jsonnet/alerts.jsonnet
- jsonnet/jsonnetfile.json
- jsonnet/jsonnetfile.lock.json
- jsonnet/mixin/alerts/alerts.libsonnet
moved the jb jsonnet files in the jsonnet folder as otherwise jb install deletes everything in the root vendor dir.
to generate from within the jsonnet dir
`jsonnet -J vendor alerts.jsonnet | gojsontoyaml > http-request-latency-burnrate.yaml`
I will add  alerts for all endpoint in the same PR after you check this first one.
cc @kakkoyun , @metalmatze
> Add latency and error Alerts

- Makefile
- README.md
- examples/manifests/deployment.yaml
- internal/proxy/proxy.go
- internal/server/option.go
- internal/server/server.go
- jsonnet/lib/observatorium-api.libsonnet
- jsonnet/main.jsonnet
- main.go
- prober/prober.go
- test/integration.sh
This PR changes API URL scheme from `/api/v1/metrics/` to `/api/metrics/v1`, `{interface}/{domain}/{version}`
There are a couple of reasons that justify these changes:
* To be compatible with existing tools such as Prometheus client libraries, e,g `client_go` and Grafana
(These tools expect a base URL and they add paths such as `api/v1/query`)
* To change versions of domains independently, e.g `/api/metrics/v1` and `/api/logs/v3` 
This is a breaking change,  however, Observatorium API GW hasn't been used in production and released a stable version, so this change should be ok.
Resulting APIs that could be use from outside:
```
/api/metrics/v1/api/v1/query
/api/metrics/v1/api/v1/query_range
/api/metrics/v1/write
```
Fixes #9 , #15.
cc @brancz @metalmatze @krasi-georgiev 
* Adds a new flags …
> Change URL Scheme

- internal/server/server.go
This PR fixes broken `pprof` endpoints. They were not compatible with chi.Router
> Use chi profiler

- README.md
- internal/proxy/option.go
- internal/proxy/proxy.go
- internal/server/option.go
- internal/server/server.go
- main.go
This adds all the possible knobs to be more flexible for the adjustments.
Also changes the default values.
> Add timeout knobs

- internal/server/server.go
Add a legacy /api/v1/query endpoint so that clients using the current API aren't broken by the Observatorium API being put in place.
/cc @squat @kakkoyun @brancz
> Add a legacy /api/v1/query endpoint

- internal/server/server.go
Next to adding the `/api/v1/query_range` endpoint too, the handlers are now simple handlers accepting every verb and then letting the downstream service decide on accepting or declining requests with specific verbs.
/cc @squat @kakkoyun @brancz
> Add query and query_range as generic handlers forwarding all verbs

- .circleci/config.yml
- Makefile
* Only trigger release job for SemVer tags
The job gets triggered for all master merges, we just want it to get triggered with tagged versions.
https://quay.io/repository/observatorium/observatorium?tag=latest&tab=tags
> Only trigger release job for SemVer tags

- .circleci/config.yml
Currently, we run two workflows on every PR, build_and_test and
commit-master, both of which run all tests. This mistake was also
present in observatorium/configuration and was cleaned up in
https://github.com/observatorium/configuration/pull/241.
cc @metalmatze @kakkoyun 
> .circleci: clean up config

- README.md
- go.mod
- internal/api/metrics/legacy/http.go
- internal/api/metrics/v1/http.go
- internal/authentication/http.go
- internal/authorization/http.go
- main.go
- rbac/rbac.go
- test/config/rbac.yaml
- test/config/tenants.yaml
- test/integration.sh
- vendor/modules.txt
This commit implements and utilizes an authorization middleware to limit
API usage to subjects who have access to resources belonging to a
tenant, as specified in an RBAC configuration file.
At the heart of it, this commit simply ties the existing rbac.Authorizer
interface to a middleware. One implementation detail is that in order to
identify a subject, we need to find a username from the OIDC token. We
now allow the tenant to specify the field that should be used to
uniquely identify subjects, just as the Kubernetes apiserver does
with its `--oidc-username-claim` flag. The subject's name wil default to
the value of the `sub` field, but can be changed to, e.g., `email` in
order to have nicer usernames in RBAC role bindings.
cc …
> internal/authorization: create authz middleware

- .circleci/config.yml
Currently, merging to master triggers the tagged-master job, because it
seems that CircleCI filters are ORed. This causes the Makefile to try to
tag a docker container with a trailing `:` since the Git tag is emtpy.
This commit changes the logic so that the tagged-master job is only
triggered on a valid SemVer tag.
cc @kakkoyun
> .circleci: fix tagged master job

- .circleci/config.yml
- Makefile
- README.md
- examples/main.jsonnet
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- internal/api/logs/v1/http.go
- jsonnet/lib/observatorium-api.libsonnet
- main.go
- test/config/loki.yml
- test/config/rbac.yaml
- test/integration.sh
This PR adds proxy support to Loki `/loki/api/v1/{query, query_range, push}` and `/ready` endpoints. In addition it extends the api gateway CLI parameters to declare a read and write endpoint for the Loki.
> Add loki query and push proxy support

- README.md
- main.go
This commit simply cleans up the grammar for the flag descriptions.
cc @metalmatze
> main.go: clean up flags

- examples/rbac/simple.yaml
- examples/tenants/simple.yaml
This commit adds an example RBAC configuration and shows a new field in
the tenant configuration.
cc @metalmatze
> examples: add rbac example

- examples/main.jsonnet
- examples/manifests/configmap-with-tls.yaml
- examples/manifests/configmap.yaml
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- examples/manifests/secret-with-tls.yaml
- examples/manifests/secret.yaml
- jsonnet/lib/observatorium-api.libsonnet
This PR adds RBAC and tenants configuration files to the generated
manifests by extending the jsonnet library for the API.
cc @metalmatze @periklis
> jsonnet,examples: add RBAC + tenants to manifests

- test/tls/generate.go
This patch adds a missing call to Parse()[1],
so cmd line arguments will get processed, making
the created certificates valid for additional use cases.
Issue: #54
[1] https://gobyexample.com/command-line-flags
> Process cmd line arguments in generate-tls-cert

- Makefile
The old Shellcheck download location is no longer valid.
xref: https://github.com/koalaman/shellcheck/issues/1871
cc @kakkoyun @metalmatze
> Makefile: update shellcheck source

- Makefile
- go.mod
- go.sum
- test/integration.sh
- tools.go
- vendor/modules.txt
This commit bumps the up tool to test logs ingestion thanks to
@periklis's recent updates in
https://github.com/observatorium/up/pull/16.
cc @kakkoyun @metalmatze @periklis
> test/integration.sh: use up to test logs

- README.md
cc @rollandf @metalmatze @kakkoyun 
xref: #64
> README: some improvements to readme

- README.md
- go.mod
- go.sum
- main.go
- test/integration.sh
- vendor/github.com/metalmatze/signal/healthcheck/checks.go
- vendor/modules.txt
The healthchecks from the internal server weren't supporting HTTPS calls to the public server.
We can now explicitly pass `tls.healthchecks.*` via TLS configuration flags.
/cc @squat @nmagnezi
> Add TLS support to Healthchecks

- examples/main.jsonnet
- examples/manifests/deployment-with-mtls.yaml
- examples/manifests/deployment-with-tls.yaml
- jsonnet/lib/observatorium-api.libsonnet
The reason for this change is that the operator cannot modify or append settings to existing manifests. It merely builds the config by squashing CR provided config and default config and invoke manifest generation.
The meaning of this is that the `api-deployment` manifest generator to be “smarter” and be able to append anything related to TLS settings when those are provided by the user (either manually in `config` or CR when driven by an operator).
> api-deployment manifest handling for volumes and volumeMounts

- .circleci/config.yml
- Makefile
- README.md
- internal/api/logs/v1/http.go
- main.go
- test/config/loki.yml
- test/integration.sh
This PR addresses a Loki specific distinction between read and tail requests. Read requests target the query frontend that is backed by the queriers and handles read concurrency and caching. Howeve, tail requests target the queriers directly.
**Reference:** [Grafana Gateway Configuration](https://github.com/grafana/loki/blob/master/production/ksonnet/loki/gateway.libsonnet#L43)
/cc @squat
> Add tail endpoint for logs

- README.md
- examples/main.jsonnet
- examples/manifests/deployment-with-mtls.yaml
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- jsonnet/lib/observatorium-api.libsonnet
This PR addresses the missing jsonnet manifests for support the logs tail endpoint in #70 
cc @squat
> Add logs tail endpoint to deployment manifests

- README.md
- internal/authentication/http.go
- internal/authentication/mtls.go
- internal/authentication/oidc.go
- internal/tls/config.go
- main.go
- test/config/rbac.yaml
- test/config/tenants.yaml
- test/integration.sh
- test/tls/generate.go
Currently, the Observatorium API has overlapping authentication
concepts:
* the API has a global mTLS setting to validate client certs; and
* each tenant can authenticate clients via OIDC.
It is confusing and messy that these overlap. Identify should be
mediated entirely by the mechanism chosen by the tenant and the API's
TLS configuration should provide a secure transport.
This commit removes the global mTLS settings of the API and enables
mTLS-based authentication on a per-tenant basis.
This means that each tenant can specify a separate CA to authenticate
all requests for resources they own.
> internal/authentication: enable mTLS auth

- examples/main.jsonnet
- examples/manifests/configmap-with-tls.yaml
- examples/manifests/configmap.yaml
- internal/authentication/http.go
- internal/authentication/mtls.go
- internal/authentication/oidc.go
- internal/authorization/http.go
- main.go
- rbac/rbac.go
- rbac/rbac_test.go
- test/config/rbac.yaml
- test/tls/generate.go
This commit enables specifying groups in the RBAC file so that roles can
be bound to a set of users rather than just individually per user. Groups
are discovered in OIDC using the claim specified in each tenant's OIDC
configuration. In mTLS, groups are populated from the list of the client
certificate's organizational units.
> internal,rbac: enable groups in rbac

- examples/main.jsonnet
- examples/manifests/configmap-with-tls.yaml
- examples/manifests/configmap.yaml
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- examples/manifests/secret-with-tls.yaml
- examples/manifests/secret.yaml
- examples/manifests/service-with-tls.yaml
- examples/manifests/service.yaml
This commit updates the image tag to a version that supports groups in
RBAC.
> Update image tag for groups

- internal/authentication/oidc.go
When setting a group in OIDC, we are accidentally overwriting the
context, erasing the subject. This commit fixes it.
> internal/authentication: fix ctx when oidc group

- internal/authentication/oidc.go
This commit enables the OIDC authenticator to decode groups when they
come in as a slice of empty interfaces, which is how they are go-oidc
decodes them when they come from Dex's GitHub connector.
cc @observatorium/admin
> internal/authentication: groups as interface slice

- internal/authentication/oidc.go
- main.go
- test/config/dex.yaml
- test/config/tenants.yaml
- test/integration.sh
Some OIDC IdPs serve their API over TLS with custom certificates, e.g.
the OpenShift OAuth server. This commit enables the Observatorium API to
use such IdPs as OIDC servers and adds tests to verify that this
workflow works.
> *: enable using IdP with custom CA

- internal/authentication/http.go
- internal/authentication/mtls.go
- internal/authentication/oidc.go
- main.go
Currently, if a single tenant has a broken OIDC configuration, then
entire Observatorium API will fail to start. This commit ensures that
broken configs are treated as warnings, allowing the rest of the API to
continue running. Tenants with broken configs will not be able to
authenticate and will get `bad request` responses when accessing their
URLs, since for all intents and purposes, that tenant does not actually
exist.
This code has been tested by appending a bad OIDC configuration to the
test/config/tenants.yaml file and running the integration tests.
cc @metalmatze
> internal/authentication: don't fail broken oidc

- README.md
- main.go
This commit simply fixes the whitespace in the descriptions for several
flags.
> main.go: fix flag message whitespace

- examples/main.jsonnet
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/secret-with-tls.yaml
- jsonnet/lib/observatorium-api.libsonnet
Previously, the TLS settings required configuring Jsonnet code AND
manually creating and deploying a magically-named Secret containing
the TLS data. This commit refactors this code so that the Secret is
automatically generated and mounted from provided TLS data.
The deployments PR (https://github.com/observatorium/deployments/pull/273) needs a big refactor in order to work and these changes will support and simplify that code.
cc @metalmatze
> jsonnet: make TLS settings work with K8s Secret

- README.md
- jsonnet/lib/observatorium-api.libsonnet
- main.go
Currently, the TLS configuration used by the healthchecker HTTP client
always defaults to verifying the server name of the certificate using
the hostname of the healthcheck URL. This does not work in most
production configurations, where the certificate issued by a real CA,
e.g. Let's Encrypt, only includes the domain name in the subject. This
means that verifying the subject, e.g. example.com against the hostname,
i.e. `localhost`, will always fail.
This commit enables configuring the server name to use for certificate
verification.
cc @observatorium/maintainers @clyang82
> allow setting server name in healthcheck TLS configuration

- examples/main.jsonnet
- examples/manifests/configmap-with-tls.yaml
- examples/manifests/configmap.yaml
- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- examples/manifests/secret-with-tls.yaml
- examples/manifests/secret.yaml
- examples/manifests/service-with-tls.yaml
- examples/manifests/service.yaml
- jsonnet/lib/observatorium-api.libsonnet
PR #87 was intended to decouple the deployment from a secret with a
magic, hard-coded name, but it obligated all consumers of this library
to render a secret and configmap using this jsonnet, rather than truly
decouple the deployment from the configuration files. This meant that
e.g. a custom resource for the Observatorium operator would need to have
the certificates in-line in order to render this manifest, which caused
two issues:
1. it put secrets in otherwise plain-text files; and
2. it prevented (re-)using secrets that may be created by another
service, e.g. cert-manager.
This PR fixes this by truly decoupling the deployment and the
configuration files. Now, the jsonnet accepts a secret name and keys to
specify where the API can find the certificates it needs.
Signed-off-by: Lucas …
> jsonnet: decouple deployment from secret

- internal/authentication/oidc.go
Currently, the Observatorium API can start up if a tenant's OIDC
configuration is broken. However, this introduces a nil middleware into
the middlewares map, which causes the handler to panic when a request is
received. This commit fixes this by skipping nil middlewares during
generation.
> internal/authentication: panic when no middleware

- jsonnet/lib/observatorium-api.libsonnet
Some certificate providers do not put the CA used to sign a
certificate in a ConfigMap but rather in the same Secret as the
certificate itself, e.g. cert-manager. This commit enables configuring
the CA for the Observatorium API using the same Secret that contains
the certificate and thus enables operation with cert-manager.
The logic is as follows if a caKey is given:
1. if no configMapName is provided, then mount the CA from the same
Secret as the certificate and key; else
2. if a configMapName is provided, then mount the CA from the ConfigMap.
In other words, when no configMapName is specified, the Jsonnet will
default to mounting the CA from the Secret.
cc @observatorium/maintainers @clyang82
> jsonnet: enable TLS without ConfigMap

- jsonnet/lib/observatorium-api.libsonnet
Allow mount the mTLS CA and follow this logic:
The logic is as follows if a caKey is given:
- if a SecretName is provided, then mount the CA from the SecretName.
- if a configMapName is provided, then mount the CA from the ConfigMap
And reconfigure the tenants.yaml file to have `caPath` if there is `mTLS`
/assign @squat
> Mount mtls ca

- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- examples/manifests/serviceAccount-with-tls.yaml
- examples/manifests/serviceAccount.yaml
- jsonnet/lib/observatorium-api.libsonnet
Pod analysis shows most observability pods use the default service account with cluster-admin access. A separate service account should be used by the pods so they can each be bound to only the privileges they need. None of them should be using the default service account or the wild card privileges `[map[apiGroups:[*] resources:[*] verbs:[*]] map[nonResourceURLs:[*] verbs:[*]]]` that the default service account currently uses.
> Create sa instead of use default

- test/config/dex.yaml
- test/config/tenants.yaml
- test/dex/templates/approval.html
- test/dex/templates/password.html
This PR fixes the callback URLs for local development using the OIDC
authentication method.
It also adds the bare minimum HTML to support password login and to
thus be able to use the authorization code flow with Dex locally.
> Local Development Improvements for Dex

- jsonnet/lib/observatorium-api.libsonnet
Follows up from #112 and #110 by adding support for configuring a secret containing the CA for the tenant.
﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Add support for tenant's OIDC CA configmap

- README.md
- main.go
This PR adds global throttling that controls number of currently processed requests at a time across all tenants. 
In addition to [rate-limiting per tenant](https://github.com/observatorium/observatorium/pull/102).
> Add throttle limit

- Makefile
make run was failing to find `dex`. This fixes the problem by providing the bingo path to `dex`
```
$ make run
go mod tidy
go mod download
go mod verify
all modules verified
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on GOPROXY=https://proxy.golang.org go build -a -ldflags '-s -w' -o observatorium .
PATH=$PATH:/home/brett/projects/redhat/observatorium/tmp/bin:/home/brett/.go/bin ./test/run-local.sh
-------------------------------------------
- Waiting for Dex to come up...  -
-------------------------------------------
./test/run-local.sh: line 16: dex: command not found
..................................^C./test/run-local.sh: line 1: kill: (1207933) - No such process
make: *** [Makefile:77: run] Interrupt
```
> Add dex parameter to make run target

- .gitignore
- api/logs/v1/http.go
- test/integration.sh
Add APIs to support the Loki datasource in Grafana 7 and earlier (https://grafana.com/docs/loki/latest/api/#microservices-mode).
Verified with Grafana 6 and 7.
> add log api to support Loki datasources in Grafana

- jsonnet/lib/observatorium-api.libsonnet
Exposed the recently added `internal.tracing` flags from the Jsonnet lib.
> jsonnet lib: Expose the internal tracing config

- README.md
- jsonnet/lib/observatorium-api.libsonnet
- main.go
- tracing/tracing.go
Add a flag to specify if the trace endpoint is an agent or a collector.
> Add a flag for choosing trace endpoint type

- authorization/http.go
- opa/opa.go
- rbac/rbac.go
- rbac/rbac_test.go
This PR adds support to forward the upstream authorizers' status codes to observatorium clients (e.g. prometheus remote-write, promtail). In-process authorizers (i.e. static RBAC, in-process OPA) will return as before `StatusForbidden` on any error when processing the authorization request. Upstream authorizers (i.e. OPA-AMS) will forward the status code of the upstream response if non 2xx or else `StatusForbidden` for errors processing the authorization request.
Forwarding status codes enables backpressure signaling to clients (e.g. StatusTooManyRequests) or non-retries on 400s.
/cc @squat
> Add forwarding upstream authorizer response status codes

- README.md
- main.go
With Zero backlog and backlog getting timing out immediately with 1ms, all concurrent requests beyond 'middleware.concurrent-request-limit' result in immediate non-200 HTTP response
> Return non-200 HTTP response code if concurrent API requests cross the specified concurrent-request-limit #

- authentication/mtls.go
- main.go
This  PR is to fix the issue: https://github.com/observatorium/api/issues/136
It updates CA of MTLSConfig from *x509.Certificate to []*x509.Certificate. When reading ca file, all certificates located in the ca file will be loaded and stored in MTLSConfig.CA. Later, all certificates will be added into certpool to verify the incoming request.
> support multiple certificates in mtls ca file

- api/logs/v1/http.go
- api/metrics/v1/http.go
- main.go
- proxy/proxy.go
With this PR, Obs. API will forward the tenant prefix we strip from the incoming requests (for ex. `/api/metrics/v1/{tenant}/` for metrics API) to the upstream using a HTTP header. The header key is configurable and the default is `X-Forwarded-Prefix`, which is not a standard, but is widely used for the same purpose (e.g. in Traefik).
This forwarding is useful if the upstream applications wants to do some redirection, if they serve a UI, etc. The immediate use case is for serving the Thanos UI properly.
> Forward the tenant prefix with all requests to upstream

- api/logs/v1/http.go
This PR will allow observatorium-api to expose Loki's Series API (See [Docs](https://grafana.com/docs/loki/latest/api/#series)). This enables users to queries for series directly (e.g. `logcli series`) as well as administrators to analyze labels for cardinality (e.g. `logcli series --analyze-labels`).
> Expose loki series api for logs endpoint

- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- main.go
The `uiProxy` and `proxyRead` in metrics API were using the same set of `readMiddlerwares`. Due to this the Obs. API was trying to enforce tenant label on UI/assets requests as well. This resulted in all UI requests failing with error "query not found".
- This PR introduced new option `UIMiddleware` and uses this instead of the `ReadMiddleware` for UI.
- This PR also fixes the missing label enforcing middleware for the legacy API as well.
> Do not attempt to enforce tenant label on UI endpoints

- proxy/proxy.go
This change will allow tenants to use their own reverse proxies and still be able to view the UI properly as they can override the prefix header according to their needs.
> Do not override the prefix header if it's already set

- api/metrics/v1/tenant_isolation.go
- authorization/http.go
- main.go
As per `WithEnforceTenantLabel` assuming PromQL specific queries, this function belongs better to `api/metrics/v1` pkg.
> Move metrics tenant isolation to metrics v1 pkg

- examples/rbac/simple.yaml
Although the example RBAC config is not being used anywhere _per se_, experimenting with and trying to run the API 'plainly' with example YAMLs should work. Currently that is not the case due to:
```
api ❯ ./observatorium-api --metrics.read.endpoint=http://localhost:9090 --log.level=debug --tenants.config=./examples/tenants/simple.yaml --rbac.config=./examples/rbac/simple.yaml                            main
2021/07/13 11:44:18 unable to read RBAC YAML: could not parse RBAC data: error unmarshaling JSON: json: cannot unmarshal string into Go struct field RoleBinding.roleBindings.subjects of type rbac.Subject
```
This PR provides a small update to make it work.
> Update the RBAC example

- Makefile
- test/integration.sh
- test/run-local.sh
While doing some local manual testing, I noticed that the currently used version of Thanos in integration tests is `0.13.0` whereas the latest stable version is [`0.21.1`](https://github.com/thanos-io/thanos/releases/tag/v0.21.1) (which explained some discrepancies between my manual tests vs. running tests via `make test`).
Includes additional changes to test script that reflect changes in Thanos configuration (e.g. passing label to receiver).
> test: Use latest stable Thanos version for integration tests

- go.mod
- ratelimit/client.go
- ratelimit/http.go
- ratelimit/http_test.go
In light of the fact that we are increasing activity in the repository, working with and refactoring the existing code, and with regards to previous discussions in https://github.com/observatorium/api/pull/146#discussion_r676417635, it would be useful to increase test coverage in the repository.
This PR starts by adding unit tests for local and shared rate limiter.
> tests: Add unit tests for rate limiter

- Makefile
- api/logs/v1/http.go
- test/integration.sh
This is a follow up to https://github.com/observatorium/api/pull/154 which attempted to fix the failing log tail tests (related issue - https://github.com/observatorium/api/issues/153).
Fixes:
1. Incorrect write / tail paths in the integration test, which where resulting in `404`
2. Removes tracing instrumentation from the tail reverse proxy, which is resulting in another failure, when trying to tail logs via websocket (excerpt):
```
level=debug name=observatorium ts=2021-08-11T09:09:25.089037723Z caller=proxy.go:61 request=mgera.remote.csb/MnzOda8mO5-000071 msg="request to upstream" url="http://127.0.0.1:3100/loki/api/v1/tail?query=%7Bfoo%3D%22bar%22%2C__name__%3D%22up_test%22%7D"
level=warn name=observatorium ts=2021-08-11T09:09:25.090372901Z caller=stdlib.go:89 …
```
> tests: Additional fixes for tail logs integration test

- authentication/http.go
- authorization/http.go
- main.go
- opa/opa.go
- rbac/rbac.go
- rbac/rbac_test.go
This change set introduces support to forward the original user bearer token from the `observatorium-api` to the `opa-authorizer`. Some authorizer implementations need the original token to talk to the target authorization endpoint, e.g. `opa-openshift` talks to the OpenShift API server to request the users' namespaces.
In detail, the user bearer token pass-through can be configured per tenant and is send via the `X-Forwarded-Access-Token` header.
> Add support to forward the original bearer token to the authorizer

- Dockerfile
The labels were dropped by mistake in https://github.com/observatorium/api/pull/160. This PR re-adds them.
> Dockerfile: Add mistakenly dropped labels again

- .circleci/config.yml
It seems that after https://github.com/observatorium/api/pull/166, pushing images to Quay is broken (see failed workflow https://app.circleci.com/pipelines/github/observatorium/api/164/workflows/12129f16-5980-4887-9bc0-7a14451105d9/jobs/710). 
This is due to change in the version of Alpine image used, see discussion https://discuss.circleci.com/t/unable-to-use-make/40552/2.
To fix the issue, this PR updates the image used by the CircleCI machine executor to the latest Ubuntu image, which includes the required minimal Docker version (which is [`v20.10.7`](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images); per [Alpine notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2) minimum …
> Update CircleCI machine image to fix Docker image build

- Dockerfile
After https://github.com/observatorium/api/pull/166 , I forgot to update also the alpine version from the runner base image - so this PR fixes that
> Dockerfile: Update runner version

- .golangci.yml
- Makefile
- api/logs/v1/http.go
- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- api/metrics/v1/tenant_isolation.go
- main.go
- test/e2e/metrics_test.go
- test/e2e/services.go
Also:
* Renamed all option function to `With...`.
* Extended tests to test new methods.
* Moved to special docker tag (local_e2e_test) so we don't by mistake run e2e tests against some random latest
image.
Before changes tests were failing with (zero isolation):
```
exp: v1.Warnings{"No StoreAPIs matched for this query"}
got: v1.Warnings(nil)
```
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
> metrics: Added labels + series methods to tenancy isolated paths.

- authentication/oidc.go
Re-adds logging to ensure we have detailed information if the OIDC registration is failing.
> Log failed OIDC registration attempts

- authentication/authentication.go
- go.mod
- go.sum
- main.go
- server/paths.go
This PR adds a new handler for `/` to return a list of available API paths. The purpose of this is to improve discoverability of the API paths and to improve the user experience.
The changes also including bumping the `signal` packaged user for internal server and adds some missing docs.
> List available paths on root path

- authentication/oidc.go
Currently, if a user goes through the authentication flow in the browser, the last step is to call `/callback` endpooint, which subsequently redirects user further with authentication set up. However, at the moment we are not setting any redirect URL, causing the user to end up at route `/oidc/{tenant}`, which does not exist.
This PR adjusts the flow to redirect the user to `/{tenant}` which in turn redirects to the Thanos UI (`/graph` endpoint), which is much better user experience.
Tested locally.
> OIDC Auth: Redirect to a valid URL after `/callback`

- main.go
If an issue with a tenant configuration occurs, that prevents the tenant from being configured on the API start up, we do not interrupt the process, since we still want the API to come up with the rest of correctly configured tenants. We only issue a warning for tenants which could not be configured.
To increase the visibility of such issue, this PR introduces a metric to track any tenants skipped due to misconfiguration.
> Add metric for skipped tenant configuration

- api/metrics/v1/rules.go
This commit fixes two bugs where a failed HTTP request from the rules
client can cause a panic in the Observatorium API.
1. status codes were read prematurely when the HTTP response may have
been nil, causing a panic; and
2. the set handler did not return after a failed request, causing the
HTTP response to be set twice.
It also fixes a formatting bug in the HTTP status where an extraneous
`%w` was printed.
> api/metrics/v1: fix rules panic

- Makefile
We have a report that running the interactive and E2E tests does not work on MacOS, which is due to the fact that we use single stage Docker build for local tests and simply copy the built API binary into the image. This does not work for e.g. MacOS users.
The fix is to use the 'full' build for other OS users and build the API for right platform instead of copying the binary.
Resolves #189.
> Makefile: Adjust `container-test` target to work for MacOS

- Makefile
- api/metrics/v1/http.go
- api/metrics/v1/rules.go
- go.mod
- main.go
- rules/custom_types.go
- rules/custom_types_test.go
- rules/rules.go
- rules/spec.yaml
Currently, recording and alerting rules that are fetched from the new
rules/raw API will not have any tenant label attached to them. This
means that when the rules are configured on a Thanos Ruler, the time
series that are generated will not have a tenant label on them. This is
a big problem, because without this tenant label, the very tenant to
whom the rules belong cannot query for the time series, making them in
effect useless. This PR enforces that all rules returned by the
rules/raw endpoint have a tenant_id label attached to them.
Note: this is a distinct problem from ensuring that the rules written by
a tenant are guaranteed to only include data from that tenant.
Currently, the rules from a tenant can select data from any tenant. This
is a distinct problem and should absolutely be …
> Enforce Labels on Returned Rules

- authorization/http.go
- main.go
- rbac/rbac.go
- rbac/rbac_test.go
It is quite difficult to debug 403 problems.  This allows the admin to see the problems.
For example, when I tried to substitute Keycloak as OIDC provider, I must have misconfigured it.  Without this PR, nothing is logged and the user just sees "403".  With this log the user sees "403 authorization declined", which gives a hint to where to look in the code.
The **admin** sees 
```
tenant "test-oidc" unknown; valid tenants are map[test:{map[{admin@example.com user}:{}] map[{admin@example.com user}:{}]}]
```
(Probably this currently logs too much.  That is another TODO)
> Debug problems of authorization

- rules/rules.go
- rules/spec.yaml
Following up on the discussion [here](https://github.com/observatorium/thanos-rule-syncer/pull/8#pullrequestreview-841868405) this PR extends the rules backend spec with another endpoint to return rules for all tenants.
I also changes the previous path to return rules for a tenant from `/api/v1/{tenant}/rules` to `/api/v1/rules/{tenant}`, because the previous format scoped everything under this API to a tenant.
Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>
> rules spec: Add an endpoint to return rules for all tenants

- authentication/mtls.go
- authentication/oidc.go
- authentication/openshift.go
- go.mod
- go.sum
- opa/opa.go
- opa/opa_test.go
This commit introduces support for having pluggable rego custom built-in
functions in Go, this allows adapters to extend OPA in-process with
custom authorization logic.
Signed-off-by: Neyyan Sony <neyysony@in.ibm.com>
> Introduce support for pluggable rego custom built-in functions in go

- .github/dependabot.yml
This would help speed up bumping dependencies to avoid any
vulnerabilities.
> Introduce dependabot config

- ratelimit/client.go
Seems like one more lint issue went uncaught during previous dependency update - fixing it here to replace deprecated gRPC dial option. See also: https://pkg.go.dev/google.golang.org/grpc#WithInsecure
> Replace deprecated gRPC dial option

- api/metrics/v1/rules.go
Currently, the API returns 200 status codes for all responses of the rules client. So even if the rules file in a PUT request is invalid, API returns 200 with the body `request body failed rule group validation` as observed in #198.
This PR ensures that the correct HTTP status code received from the rules client is propagated by the API, for the `rules/raw` endpoint.
Fixes [MON-2176](https://issues.redhat.com/browse/MON-2176).
> Propagate rules client status code

- api/metrics/v1/rules.go
- test/e2e/configs.go
- test/e2e/rules_test.go
Currently, we enforce tenant labels on rules by adding the labels to them when Observatorium API gets it from the rules storage client i.e, the rules will only have the tenant labels when we get it from the API `rules/raw` endpoint.
With the recent changes in thanos-rule-syncer and rules-objstore, this means,
- Observatorium API doesn’t add a tenant label while writing rules to rules-objstore
- With the `listallrules` endpoint, thanos-rule-syncer will try to get all rules by hitting rules-objstore directly (so enforcing labels won’t work as we’re no longer relying on the API read path, but read from rules-objstore directly)
- So the rule file generated by thanos-rule-syncer, which is to be used by Thanos Ruler won’t have any tenant labels, so any resultant series will also not have labels …
> Enforce tenant labels on rule storage PUT request

- test/e2e/interactive_test.go
- test/e2e/rules_test.go
Adds rules service to run when running the interactive setup.
> Interactive test: Run rules services as part of the interactive test

- api/metrics/v1/http.go
Currently, a call to the `/api/metrics/v1/{tenant}/api/v1/rules` endpoint, returns rules for all tenants, as it proxies the request to Thanos Querier.
This PR adds tenant isolation to `/api/metrics/v1/{tenant}/api/v1/rules` endpoint, by adapting [`prom-label-proxy`](https://github.com/prometheus-community/prom-label-proxy) code to modify the API response from the Thanos Query `api/v1/rules` endpoint and filter via the tenant label (this is possible as we [enforce tenant labels on rules](https://github.com/observatorium/api/pull/191)). So each tenant can only retrieve their own rules.
Relevant issue: https://issues.redhat.com/browse/MON-2141
> Add matcher based tenancy to api/v1/rules

- api/metrics/v1/rules.go
- test/e2e/configs.go
- test/e2e/rules_test.go
To help with tenant rules validation (as mentioned in https://github.com/observatorium/api/issues/194), this PR adds a `tenant_id` label to metrics present in a `expr` field in a recording/alerting rule that is written via the Rules API (via `/api/v1/rules/raw` endpoint)
So for the following rule that is written via Rules API:
```yaml
groups:
- name: node_rules
interval: 30s
rules:
- record: job:up:avg
expr: avg without(instance)(up{job="node"})
- alert: ManyInstancesDown
expr: job:up:avg{job="node"} < 0.5
for: 10m
annotations:
Summary: Many instances down
```
We expect that when the rule is read via `GET` request, the rule is changed and a `tenant_id` label is appended to `up` and `avg`:
`expr: avg without(instance)(up{job="node",tenant_id="tenantIDHere"})`
`expr: …
> Rules API: Enforce tenant label and id in rule expression

- main.go
Add handlerFunc to block methods with chi router with methodNotAllowed
> Allow specific method access for endpoints

- README.md
- api/traces/v1/api.go
- authentication/authentication.go
- authentication/authentication_test.go
- authentication/grpc.go
- authentication/mtls.go
- authentication/oidc.go
- authentication/openshift.go
- authorization/grpc.go
- go.mod
- go.sum
- jsonnet/lib/observatorium-api.libsonnet
- main.go
Signed-off-by: Ed Snible <snible@us.ibm.com>
This PR creates an Open Telemetry gRPC endpoint for the method `/opentelemetry.proto.collector.trace.v1.TraceService/Export`.  **This proof-of-concept does not (yet) contain RBAC security or tenancy.**  This version uses https://github.com/mwitkow/grpc-proxy to proxy the gRPC without deserializing it.
Previously I created [pull 196](https://github.com/observatorium/api/pull/196) which exposed the OTLP Trace **HTTP** endpoint.  That was straightforward using the Chi-router.
The final implementation needs RBAC and tenancy.  I haven't yet found anything that is the equivalent to the `chi.Router` for gRPC.  Maybe https://github.com/grpc-ecosystem/go-grpc-middleware ?
It is too early to review this code, beyond the architectural ideas and the choice …
> GRPC trace API

- examples/manifests/deployment-with-tls.yaml
- examples/manifests/deployment.yaml
- examples/manifests/service-with-tls.yaml
- examples/manifests/service.yaml
- jsonnet/lib/observatorium-api.libsonnet
The port name cannot be upper case:
```
Error from server (Invalid): error when creating "manifests/api-deployment.yaml": Deployment.apps "observatorium-xyz-observatorium-api" is invalid: spec.template.spec.containers[0].ports[2].name: Invalid value: "publicGrpc": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-)
Error from server (Invalid): error when creating "manifests/api-service.yaml": Service "observatorium-xyz-observatorium-api" is invalid: spec.ports[2].name: Invalid value: "publicGrpc": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is …
```
> Fix grpc port name by making it lowercase

- test/e2e/interactive_test.go
This PR adds trace receiving to TestInteractive.
This starts an Open Telemetry collector that forwards to a Jaeger with memory-only storage.
This enables Observatorium to listen for GRPC, and to forward to that OTel collector.
Note that this configuration is merely for testing; the memory-only Jaeger does not support tenancy or persist traces.
To actually run the test you'll need to check out https://github.com/open-telemetry/opentelemetry-proto because neither Observatorium nor OTel support gRPC reflection.
To run the test first `go test -v --tags=interactive -test.timeout=9999m -run TestInteractiveSetup ./test/e2e/.`.  (The `-v` is important, otherwise you don't see the ports and logs.)
(The test outputs important ports and an OIDC token.  It then outputs logs continuously -- you may …
> Add trace recieving to TestInteractive

- README.md
- api/traces/v1/http.go
- main.go
- proxy/proxy.go
- test/e2e/interactive_test.go
- test/e2e/services.go
- test/e2e/traces_test.go
This PR adds proxying of the Jaeger V2 HTTP query API and the Jaeger UI assets.
With this change, the Jaeger UI is available at http://localhost:8080/api/traces/v1/test-oidc/search/
Note that the first time logging in, it redirects away from traces.  Not sure if that is correct or not.
Note that there are currently no multi-tenant backends for Jaeger, so the UI currently sees all traces.  The work to divide the tenants will be done in Jaeger itself or another front-end, probably not in observatorium/api.
> Trace query API

- README.md
- api/traces/v1/api.go
- api/traces/v1/http.go
- jsonnet/lib/observatorium-api.libsonnet
- main.go
- test/e2e/configs.go
- test/e2e/helpers.go
- test/e2e/services.go
- test/e2e/traces_test.go
Signed-off-by: Ed Snible <snible@us.ibm.com>
Resolves https://github.com/observatorium/api/issues/267 allowing Jaeger query hosts to be specified in Jsonnet.
Resolves https://github.com/observatorium/api/issues/268 by allowing the `-traces.read.endpoint` to describe multiple single-tenant Jaeger instances.  For example, we can say `-traces.read.endpoint=http://jaeger-{tenant}-query:16686`.  (This uses the same convention we use in the configuration of the OTel processor.)
With this implementation, Observatorium can provide all tenants with their own Jaeger instance.  In the future, when Jaeger itself supports tenancy, we simply change the read endpoint to point to the multi-tenant Jaeger.
cc @pavolloffay
> Pseudo-tenancy for trace queries

- client/client.gen.go
- client/parameters/parameters.gen.go
- client/parameters/parameters.yaml
- client/spec.yaml
This PR adds `optionalSeriesMatcher` parameter in the oapi spec to use in endpoints like /api/v1/labels and /api/v1/label/{name}/values.
> Add optional series matcher in spec

- server/http_instrumentation.go
In #295 accidentally some histograms and summaries weren't added to the Prometheus registry.
Signed-off-by: Douglas Camata <159076+douglascamata@users.noreply.github.com>
> Add summaries and histograms to the registry

- api/metrics/v1/labels_enforcer.go
We have noticed that if a user is providing an invalid query to the API on the read path, this will result in HTTP response `500`. This is due to the fact that when we are enforcing labels and parsing the query, we are considering this to be an server error, which it is not. Since method `enforceQueryValues` can fail only if given invalid input, I'd suggest changing this the response to bad request to indicate to the user the error is on their side.
> Label Enforcer: If parsing fails, change HTTP status code to bad request

- authentication/authentication.go
- authentication/authentication_test.go
This PR includes two commits aimed at cleaning up the naming in the authentication/authentication.go file:
- authentication: clarify naming
This commit makes the naming within the `InitializeProvider` func follow go conventions of naming to clarify the intent of the named identifier.
- authentication: use consistent naming
This commit tries to standardize the naming of the `authenticator` variable and renames it internally within the `authentication` package as a `provider`.
> authentication: clean up naming

- api/logs/v1/labels_enforcer.go
- api/metrics/v1/labels_enforcer.go
- api/metrics/v1/rules.go
- authentication/authentication.go
- authentication/http.go
- authentication/mtls.go
- authentication/oidc.go
- authentication/openshift.go
- authorization/http.go
- httperr/httperr.go
- main.go
- ratelimit/http.go
- utils/utils.go
This PR addresses #319 and ensures that all `4xx`/`5xx` responses from Observatorium API are sent in Prometheus API JSON format instead of plaintext, by taking inspiration from https://github.com/prometheus-community/prom-label-proxy/pull/108. This makes debugging via downstream UI/clients much easier.
Thus for a faulty query,
Response before, 
```
could not enforce labels: parse expr error: 1:12: parse error: unterminated quoted string
```
Response after,
```json
{"error":"could not enforce labels: parse expr error: 1:12: parse error: unterminated quoted string","errorType":"observatorium-api","status":"error"}
```
Loki is also [compatible](https://grafana.com/docs/loki/latest/api/) with Prometheus API result format, so we can use the same `PrometheusAPIError` method in …
> Return errors in Prometheus HTTP API format

- authentication/http.go
The `Add` function adds another header on top of what is already there,
that means if a client sets that header, it would be picked up by loki.
This commit changes it to Set to make sure we overwrite the header if it
is provided.
> Overwrite tenant id header

- Dockerfile
This PR defines the USER in the Dockerfile as 10000. When running the image as nonroot in Kubernetes, the resulting pod(s) will have a CreateContainerConfigError. This is because the USER in the image is not defined and assumed to be root.
The work around for this in Kubernetes is to define the user to be some non-zero user. However, as the image does not require any elevated privileges, it would be nice to make it work with the non-root user specification. This is relevant to the Kubernetes Pod Security Admission changes, which require a number of changes to be compliant with the `restricted` policy.
ref: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
> Running as non-root in Kubernetes

- client/client.gen.go
- client/parameters/parameters.gen.go
- client/parameters/parameters.yaml
- client/spec.yaml
This PR adds `dedup` and `partial_response` to Query API spec.
> Add dedup and partial_response query params to spec

- api/metrics/v1/labels_enforcer.go
- api/metrics/v1/rules.go
- api/traces/v1/http.go
- authentication/mtls.go
- authentication/oidc.go
- authentication/openshift/discovery.go
- main.go
- opa/opa.go
- opa/opa_test.go
- rbac/rbac.go
- test/e2e/configs.go
- test/e2e/helpers.go
- test/e2e/logs_test.go
- test/e2e/rules_test.go
- test/e2e/traces_test.go
- test/testtls/generate.go
This PR removes the usage of `ioutil` package, which has been deprecated: https://go.dev/doc/go1.16#ioutil.
`ioutil` is still however used in generated files (rules.go, client,go).
> Remove usage of io/ioutil

- README.md
- api/logs/v1/http.go
- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- api/traces/v1/http.go
- main.go
- tls/config.go
The following PR adds support to reverse proxy calls to metrics/logs/traces endpoints using mTLS. The purpose for this to support for example a Loki cluster that is secured via mTLS on an isolated environment. In detail, Loki does not support any native authentication methods on the HTTP layer.
> Add mTLS support for upstream servers

- client/client.gen.go
- client/models/models.gen.go
- client/models/models.yaml
- client/parameters/parameters.gen.go
- client/parameters/parameters.yaml
- client/responses/responses.gen.go
- client/responses/responses.yaml
- client/spec.yaml
The following PR extends the client API spec with all remaining rules APIs for retrieving/manipulating Logs-based rules.
> Add logs rules client api spec

- go.mod
- tls/config.go
This PR removes the `k8s.io/component-base` dependency in favor of a manual lookup for the TLS variables. `component-base` and `apiserver` rely on old versions of `otel`. This causes problems when trying to upgrade the k8s dependencies. Since `component-base` is only required to look up the TLS variables, it makes sense to replace it to reduce the number of dependencies which rely on this old library version.
> Remove component-base for manual implementation

- tls/config.go
This is a follow-up patch to #396. When there is no cipher suite set, an empty array would be set in for the `TLSConfig`. Instead, this should be nil so that the default list of cipher suites are used instead.
> Fix default TLS cipher configuration when none are specified

- Makefile
- go.sum
It seems we're hitting an issue with updating dependencies in https://github.com/observatorium/api/pull/408 due to module graph pruning and changes between 1.16 and 1.17 (https://go.dev/ref/mod#graph-pruning). Relevant output:
```
github.com/observatorium/api imports
github.com/ghodss/yaml imports
gopkg.in/yaml.v2 tested by
gopkg.in/yaml.v2.test imports
gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20200227125254-8fa46927fb4f,
but go 1.16 would select v1.0.0-20201130134442-10cb98267c6c
To upgrade to the versions selected by go 1.16:
go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
go mod tidy -compat=1.17
For other options, see:
https://golang.org/doc/modules/pruning
```
I believe we're …
> *: Use 1.17 compatibility for go mod

- Makefile
- go.mod
Follow up to https://github.com/observatorium/api/pull/409.
The issue is that dependabot uses `go mod tidy` without the parameter to ensure compatibility with 1.17 module graph pruning (`-compat=1.17`). One example of affected PR: https://github.com/observatorium/api/pull/408.
Since it's not possible customize dependabot command, next best solution is to bump `go.mod` to 1.18 even though we don't strictly require it. This sidesteps the issue as with 1.18 it's not necessary to use the `-compat` parameter (see last paragraph in https://go.dev/ref/mod#graph-pruning).
> *: Bump go.mod to 1.18 to fix dependabot issues

- main.go
> Ensure rate limiting middleware called before any paths are stripped

- ratelimit/http.go
Gubernator's duration parameter should be in milliseconds, according to their own documentation: https://github.com/mailgun/gubernator/blob/v1.0.1-rc.1/README.md?plain=1#L41.
Unfortunately I cannot add an e2e test for this right now because:
* This is is kind of urgent. 
* The e2e tests aren't (yet) arm64 friendly and I work on arm64. 
* To make them arm64 friendly we need to upgrade github.com/efficientgo dependencies (there are breaking changes) and potentially create multi-arch images for other projects in this org. I created #423 to track this.
I found the problem and solution by spinning up Gubernator and manually calling the gRPC service.
> Fix rate limiter window duration

- logql/v2/ast.go
- logql/v2/ast_test.go
- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/lexer.go
- logql/v2/parser_test.go
Parsing aliased filter expression like this:
```
{ kubernetes_pod_name="logger-5d89f8d985-4pxm4" } | json | level=~"critical|emerg|fatal|alert|crit" 
```
resulted into the wrong expression missing the `level=~` alias:
```
{ kubernetes_pod_name="logger-5d89f8d985-4pxm4" } | json | "critical|emerg|fatal|alert|crit" 
```
Ref [LOG-3397](https://issues.redhat.com/browse/LOG-3397)
cc @xperimental
> Fix parsing LogQL aliased filter expressions

- authentication/grpc.go
> Align gRPC middleware with HTTP to send tenant ID upstream 

- logql/v2/ast.go
- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/parser_test.go
The following PR implements parsing nested label filters as: 
`{label="value"} | json | level="info" level="error"`
`{label="value"} | json | level="info" and level="error"`
`{label="value"} | json | level="info" or level="error"`
`{label="value"} | json | level="info",  level="error"`
In addition it simplifies the internal AST for pipeline stages by removing unnecessary nesting structs (e.g. `LogFiltersExpr` and `LogPipelineStageExpr`). Every pipeline stage implementation requires to implement the `LogStageExpr` interface.
Fixes: [LOG-3397](https://issues.redhat.com/browse/LOG-3397) and [LOG-3441](https://issues.redhat.com/browse/LOG-3441)
/cc @xperimental
> logql: Fix parsing nested label filter expressions

- api/metrics/v1/http.go
After #430, a bug was introduced whereby `/api/metrics/v1/<tenant>/api/v1/rules` GET requests were being handled by the rules/raw GET handler instead of the `proxyRead` handler.
This led to /api/v1/rules response being only YAML and without rule health data. On Querier UI this shows up as,
In our e2e tests, we don't start Thanos Ruler and hence don't check this endpoint, will add one in next PRs (as it needs some refactoring).
> Fix `/api/v1/rules` endpoint to return correct response

- Makefile
- api/logs/v1/labels_enforcer.go
- go.mod
- logql/v2/ast.go
- logql/v2/ast_test.go
- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/parser_test.go
JIRA: https://issues.redhat.com/browse/NETOBSERV-171
In short, without this PR, only one matcher injection for multi-tenancy is allowed: e.g. `namespace=foo`
NetObserv is an observability solution dedicated to the network, that stores flow logs in Loki. Implementing multi-tenancy for NetObserv requires injecting more complex matchers for handling flow logs sources and destinations: e.g.
`src-namespace=foo OR dst-namespace=foo` (as a single query injection).
Changes:
- Updated result data from OPA Authz (**OPA breaking change**)
- Query injection needs to handle several matchers, and logical OR
- Fix string escaping issue in Loki reencoder
- Add a few tests
- As an aside, allow building with podman
Related PRs:
- https://github.com/observatorium/opa-openshift/pull/15
- …
> Allow multiple matchers for NetObserv multi-tenancy (NETOBSERV-171)

- api/logs/v1/http.go
- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- api/traces/v1/http.go
- main.go
Previously the per signal handlers used arbitrary chosen timeout values to express how long a proxied request to the corresponding upstream should take. However due to conceptual misunderstandings (e.g. request read timeout set as dialer timeout) or global middleware configuration (e.g. `middleware.Timeout(2 * time.Minute)`) the effective timeout was set to **2 Minutes** (configured in the `http.Server.WriteTimeout`). 
In general the current behavior treats all signal handlers equally and in turn unfairly. For example range queries to Loki can in general take longer than those to Thanos, because processing logs (e.g. parsing, filtering, aggregating) might take longer. I
The following implementation splits the timeouts per signal handler group (logs, metrics, traces) and keeps for sanity …
> Split request timeouts per signal handler

- api/logs/v1/rules.go
The Unified Alerting UI on Grafana is using extensively blackbox probing to discover ruler support across supported datasources, especially the ones that implement the Prometheus Rules API. In #388 we introduced the capability to enforce that the rules namespace is always the same as the tenant. This applies in managed use cases like the Loki Operator where we control in predefined tenant modes (i.e. `openshift-logging`, `openshift-network`) the amount and naming of tenants. For example in `openshift-logging` we have predefined tenants `application`, `infrastructure` and `audit` which map one to one to the allowed rules namespaces.
_Reminder_: Namespaces in Loki Ruler represent simply filesystem directory when local storage is used, e.g. when mounting the rules through a Kubernetes …
> Add support for Grafana Loki Ruler discovery when enforcing tenants

- README.md
- main.go
Follow-up PR for #493 to expose timeout configuration per CLI flags.
Ref: [LOG-4044](https://issues.redhat.com/browse/LOG-4044)
cc @xperimental
> Expose HTTP timeout options as flags

- api/logs/v1/labels_enforcer.go
- api/logs/v1/labels_enforcer_test.go
- logql/v2/ast.go
**What this PR does / why we need it**:
The current state of the logsv1 API enforces only authorization matchers on instant and range queries. This allows to limit users to search within a tenant by rewriting the LogQL stream selectors with label matchers provided by the authorization process (e.g. limit to accessible kubernetes namespaces). However the users are still able to access all label values within a tenant (e.g. all namespace names) although they have via RBAC access only to a limited set. This issue can be characterized simply as information intrusion w/o breaking the tenancy model per se.
The following PR adds support to apply authorization label matchers to the Loki Label Values API as effective filters. It applies the label matchers to the query parameter provided by:
- …
> logsv1: Enfore authz matcher on label values

- README.md
- api/logs/v1/http.go
- api/logs/v1/rules_labels_enforcer.go
- api/logs/v1/rules_labels_enforcer_test.go
- api/logs/v1/testdata/alerts.json
- api/logs/v1/testdata/rules.json
- api/logs/v1/testdata/rules.yaml
- main.go
This PR introduces the capability to filter log-based rules by applying user-selected labels. The administrator can define which label keys are valid via a CLI flag `--logs.rules.label-filters=tenantA:label-a,label-b;tenantB;label-c` and can be used as URL query parameters. The enforcement applies on the prometheus-compatible `/prometheus/api/v1/rules` as well as on the Loki API `/loki/api/v1/rules`.
cc @xperimental @aminesnow @jgbernalp
> logs: Per tenant label-based rule filters

- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- main.go
- server/http_instrumentation.go
This PR initializes all the metrics from the **metrics** APIs (v1 and legacy) to ensure they are present on a restart of the application, even without traffic.
We were having issues with the Pyrra SLOs firing the `SLOMetricAbsent` in these scenarios. This should prevent these alerts.
A small refactor was done to stop trying to guess the group and handler based on the URL path at request time. Instead, these are added through handler wrappers that store the group and handler in the context. The list of groups and handlers are used to initialize the metrics.
A bigger refactor can be done to improve this further, making the registration of the group and handler names of an endpoint initialize the metric. This will require many more changes, including changing interfaces in the code, so I …
> Initialize all handlers metrics

- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- main.go
- server/http_instrumentation.go
This fixes some issues from #547. Metrics were not properly counting due to middleware ordering, copies, and shadowing. 
Unfortunately I didn't catch this before because my e2e tests were using an old image of the project. Now this is also fixed in my environment and I can test things properly.
> Clean & fix metrics initialization 

- server/http_instrumentation.go
- server/http_instrumentation_test.go
The Labels map that is used for instrumentation is being read and wrote simultaneously by multiple goroutines, resulting in a panic.
This PR removes the need to use the same variable across different routines.
> Fix concurrent map access in HTTP instrumentation

- api/metrics/v1/http.go
r.Mount matches on a pattern, whereas r.Handle wants an exact match. For the UI route, we need to match on pattern, as we load static files and other routes via the UI route (think /store, /flags, /static etc).
This bug shows up with 404 and a `X-Content-Type-Options: nosniff` header, which is actually misleading.
> Fix UI route to match on pattern

- test/e2e/rules_test.go
This should match the behavior from rules-objstore, which is being tested in https://github.com/observatorium/rules-objstore/pull/15.
> Add e2e test for pushing empty list of rules

- authorization/query_test.go
- logql/v2/ast.go
- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/parser_test.go
This PR extends the LogQL parser to have support for nesting the whole query in parenthesis `()`. They are also reproduced when the query is recreated from AST.
Refs https://issues.redhat.com/browse/LOG-4529
> Extend LogQL parser to allow parenthesis around query

- authorization/http.go
- authorization/query.go
- main.go
This PR changes the behaviour of the "selector extraction" introduced in #555 . Instead of returning an error to the user when the extraction fails, it is just logged as a warning and processing continues as if no selectors were found.
The reasoning behind is change is that our LogQL parser might lag behind in features after the "real one" in Loki and so we might return an error for a valid query or a different error for an invalid query, because the parser implementations do not match 100%. The new code will also log the query that caused the error, so that it can be debugged.
> Do not return error when selector extraction fails

- authorization/http.go
- authorization/query.go
- authorization/rules.go
- authorization/rules_test.go
- main.go
Issue: https://issues.redhat.com/browse/LOG-4530
With the introduced middleware in https://github.com/observatorium/api/pull/555 we did not contemplate the rules api which resulted in rules requests just being denied. This PR improves the pre-existing middleware by setting the selectors based on the URL parameters if no query parameter is found.
> Fixes authorization flow for /api/logs/v1/{tenant}/rules

- README.md
- api/traces/v1/http.go
- main.go
- proxy/proxy.go
- test/e2e/configs.go
- test/e2e/helpers.go
- test/e2e/services.go
- test/e2e/traces_test.go
This PR introduces a new flag `-traces.tempo.endpoint` which should point to the **Tempo** _Query-frontend_ component in order to expose the tempo query API. (https://grafana.com/docs/tempo/latest/api_docs/) This will allow us to use the TraceQL API with the gateway.
The endpoints will be mapped according to this design document: https://docs.google.com/document/d/1vQ8F9MI8VhnqSyKjBom87axY7OIhDXeTJ4JGa9aDf9s
@pavolloffay  please review
> Expose tempo trace query API using the gateway

- go.mod
Resolves [CVE-2023-46129](https://bugzilla.redhat.com/show_bug.cgi?id=2246986)
> update github.com/nats-io/nkeys to v0.4.6

- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- ratelimit/http.go
- ratelimit/http_test.go
- server/http_instrumentation.go
https://issues.redhat.com/browse/RHOBS-914
Currently, Obs API does not have good per-tenant instrumentation to visualize requests that get rejected early (due to rate limits or other cases)
The issue is that when the rate limit middleware or other middlewares return on error, the context does not hold information about the group or handler as the labels are set when the route is handled at the end. So when the control returns back to the instrumentation handler ([line101](https://github.com/observatorium/api/blob/56abe030cbbe3e50a614dacf793fa673317b937b/server/http_instrumentation.go#L101)) the context does not hold the label values and will be reported as `unknown`. 
With this PR we ensure that the labels are set with the group and handler in context before the middlewares run and the …
> Ensure correct labels values are added during ratelimiting

- authentication/authentication.go
- authentication/oidc.go
- go.mod
- go.sum
Address underlying bump and module rename for github.com/go-jose/go-jose to address:
- https://github.com/go-jose/go-jose/security/advisories/GHSA-c5q2-7r4c-mv6g: Improper Handling of Highly Compressed Data (Data Amplification)
> chore(deps): Bump go-oidc to v3.10.0 to address transitive dep CVE

- authorization/http.go
Currently the user sees a blank page when accessing Jaeger UI, if the current user doesn't have permissions to access the specified tenant.
This PR shows the following error message instead:
```
{"error":"You don't have permission to access this tenant","errorType":"observatorium-api","status":"error"}
```
and this message for generic errors returned by Authorizer.Authorize():
```
{"error":"<status code> <status text>","errorType":"observatorium-api","status":"error"}
> Show an error message if access is denied

- README.md
- api/traces/v1/http.go
- main.go
- test/e2e/configs.go
- test/e2e/interactive_test.go
- test/e2e/services.go
- test/e2e/traces_test.go
Notable changes:
* renames `traces.write.endpoint` to `traces.write.otlpgrpc.endpoint`
* adds `traces.write.otlphttp.endpoint` 
* updates tracing images in e2e tests
> Add OTLP HTTP for traces

- logql/v2/ast.go
- logql/v2/ast_test.go
- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/lexer.go
- logql/v2/parser_test.go
Add support for LogQL features included in Loki between `2.9.8` and `v3.1.0`. Diff:
```
6df81db97 feat: Support negative numbers in LogQL (#13091)
4c88be0ef chore: update loki modules for 3.0 release (#12433)
36c703dae feat: add pattern match line filter (#12398)
cc941fe42 chore: refactor line filter MatchType (#12388)
60edfe000 Implement "or" statement in line filters (#8962)
6bced8345 [release-2.9.x] Revert "LogQL: Introduce `distinct` (#8662)" (#10358)
c030217e1 Revert "LogQL: Introduce `distinct` (#8662)" (#10356)
```
LogQL features implemented in our log api's parser:
- grafana/loki#13091
- grafana/loki#12398
- grafana/loki#8962
Refs: [LOG-5761](https://issues.redhat.com/browse/LOG-5761)
/cc @JoaoBraveCoding @jotak
> Add LogQL support for Loki v3.1.0

- README.md
- api/logs/v1/http.go
- api/metrics/legacy/http.go
- api/metrics/v1/http.go
- api/traces/v1/api.go
- api/traces/v1/http.go
- go.mod
- main.go
- tls/ca_watcer_test.go
- tls/ca_watcher.go
- tls/ca_watcher_test.go
- tls/config.go
- tls/options.go
- tls/options_test.go
This PR adds a watcher for the certificates so in case of rotation, the certificates will be reloaded.
Added flags to disable/enable this per signal, and in the general server
> Add watcher for upstreams TLS certificates

- api/logs/v1/http.go
The following PR enables the Loki OTLP route to allow ingesting logs through OTLP.
cc @pavolloffay
> Add support for logs OTLP route

- test/e2e/redis_rate_limiter_test.go
I might be wrong, but it looks to me as if one of the files in `test/e2e/` is missing the build tag that most of the others have.
I noticed this, because I tend to use `go test ./...` in most projects and this snagged on that file. I know that the workflow in this project is `make test-unit`, but it doesn't hurt when the language default continues to work.
> Fix build tag on e2e test

- logql/v2/expr.y
- logql/v2/expr.y.go
- logql/v2/parser_test.go
The logQL parser expression returns an syntax error when used with a label selector list, i.e.:
```
{log_type="application",kubernetes_namespace_name="demo-1"}|json pipeline_run_uid="kubernetes.labels.tekton_dev_pipelineRunUID" msg=".message" 
```
returns
```
failed parsing LogQL expression: syntax error: unexpected IDENTIFIER: 1:66
```
The fix enables this missing feature in the logQL parser syntax.
> fix(logql): Add missing support for json parser expr with labels

- authentication/openshift.go
When accessing the Jaeger UI, cookies are used for authentication.
At the moment, every HTTP request to the Jaeger UI prints this message
in the logs:
fallback to read cookie, no serviceaccount bearer token or mTLS certs provided
which may concern some users. Reading cookies is part of the normal operation,
therefore let's print this message only when the log level is set to debug.
> Adjust log level of 'fallback to read cookie, ...' log message

- go.mod
Follow-up to #790 to be able to continue building with Go 1.22 
PTAL @pavolloffay @philipgough
> Set minimum Go version to 1.22

- api/logs/v1/http.go
- api/logs/v1/rules_labels_enforcer.go
- api/logs/v1/rules_prometheus_labels_enforcer.go
- api/logs/v1/rules_prometheus_labels_enforcer_test.go
- main.go
In https://github.com/observatorium/api/pull/578 we completely removed the filtering code and relied only on the query parameter for Loki to filter the rules. However, the filtering only works for the Loki API and not for the Prometheus API
Fixes https://issues.redhat.com/browse/LOG-6148
> logs: re-introduce rules filtering for Prometheus API as this is still not supported by Loki
