observatorium/api

examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet

They are too specific to the actual environment.
/cc @kakkoyun

Remove resource requests and limits

---

Makefile
examples/manifests/deployment.yaml
examples/manifests/service.yaml
jsonnet/lib/observatorium-api.libsonnet
jsonnet/main.jsonnet

jsonnet: Refactor configs to comply with new conventions

---

Makefile

Add jsonnet-fmt as a lint stage

---

main.go

Fix log about UI argument

---

internal/server/server.go

Fix and refactor UI routes probably got broken while rebasing.

Fix UI routing

---

docs/benchmark.md
examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
examples/manifests/service-with-tls.yaml
examples/manifests/service.yaml
jsonnet/lib/observatorium-api.libsonnet
jsonnet/main.jsonnet
test/load.sh

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

Use API as the name everywhere to make it consistent.

---

examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet

jsonnet/lib: fix tenants secret reference

---

main.go

Increase read timeout

---

Makefile
test/integration.sh

test: Use latest stable Thanos for integration tests

---

examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet

refer to this issue - https://github.com/observatorium/deployments/issues/314

Make loki optional

---

internal/authentication/oidc.go

If the user didn't provide an Auth Bearer token nor there's a cookie available - we assume that the call was most likely a user via browser and thus redirect to the OIDC login page.

Redirect to OIDC login if no cookie

---

Makefile
test/integration.sh
test/run-local.sh

I thought that may be helpful. :)
/cc @squat @kakkoyun @periklis

Add a test/run-local.sh script run via make run for development

---

internal/authentication/oidc.go
main.go

All 4xx are debugs and all 5xx are warn logs.

Add debug and warn logs for OIDC errors

---

.circleci/config.yml
Dockerfile
Makefile

Upgrade to go 1.15

---

authentication/oidc.go
main.go

authentication: Expose OIDC NewProvider function

---

authentication/oidc.go

authentication: Refactor OIDC provider middleware and handler creation

---

jsonnet/lib/observatorium-api.libsonnet

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Fix typo in jsonnet lib: confiMap

---

main.go
ratelimit/http.go

* Add error logging
* Optimize int conversion

ratelimit: Add error logging

---

README.md
main.go
ratelimit/client.go
ratelimit/http.go
test/integration.sh

ratelimit: small cleanups to the ratelimit pkg

---

.circleci/config.yml
Makefile
examples/main.jsonnet
examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet

jsonnet: Refactor jsonnet to use functional configs

---

Makefile

Fix build command

---

.circleci/config.yml
README.md
examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml

Few generated files were missed during last PR to rename to observatorium/api.

Fix missed generated files due to recent change

---

.circleci/config.yml

*: rename default branch to main

---

examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet
main.go

This PR:
- Makes `metrics endpoint` as optional.
- fmt fixes.
/cc @periklis 
/assign @periklis 
Jira: https://issues.redhat.com/browse/LOG-1512

Make metrics endpoint as optional

---

authentication/oidc.go
main.go

This PR adds a gauge for failures during OIDC provider instantiation for tenants.

Add instrumentation for tenant registration failure

---

authentication/oidc.go

In order to have more granular information on registration failing and to make alerting work per tenant, this PR adds label for tenant name. It also temporarily removes warning log, to decrease the amount of output.

Add tenant label to OIDC registration retry counter

---

test/e2e/interactive_test.go

This adds the `newUpRun` function call to `TestInteractiveSetup` (as we do in https://github.com/observatorium/api/blob/main/test/e2e/metrics_test.go#L40) which makes it possible to get some metrics written to the receiver
Also a quick fix for the `token` var (we were fetching as the first return from `startBaseServices` instead of the second)

Add newUpRun to TestInteractiveSetup

---

examples/main.jsonnet
examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
jsonnet/lib/observatorium-api.libsonnet

This PR tries to make imagePullPolicy configurable in observatorium-api deployment.
Signed-off-by: morvencao <lcao@redhat.com>

support imagePullPolicy for observatorium-api.

---

examples/manifests/deployment-with-tls.yaml
examples/manifests/deployment.yaml
examples/manifests/service-with-tls.yaml
examples/manifests/service.yaml
jsonnet/lib/observatorium-api.libsonnet

Expose traces jsonnet configuration

---

jsonnet/lib/observatorium-api.libsonnet

Fix grpc listen address in jsonnet

---

authentication/http.go

Grafana can be paired with [oauth-proxy](https://github.com/openshift/oauth-proxy) in an OpenShift cluster for proper authentication with the cluster authentication service. While the proxy can be configured to forward the access token, it uses a custom header (`X-Forwarded-Access-Token`) which is currently not evaluated by observatorium-api.
This PR adds support for the custom header by picking it up in a middleware and passing it on to the authentication/authorization part if the `Authorization` header is empty.
The authentication code of this service uses code from `k8s.io/apiserver`. As I have not found a way to customize the bahaviour of picking up the access token from the `Authorization` header, the current implementation in this PR will add a new `Authorization` header with the …

Support reading access token from header

---

examples/manifests/service-with-tls.yaml
examples/manifests/service.yaml
jsonnet/lib/observatorium-api.libsonnet

Set appprotocol in API service jsonnet

---

api/metrics/v1/labels_enforcer.go

I have noticed strange behavior in responses to the API, when the label enforcement fails. The request got still propagated through the middleware chain all the way to the metrics backend. This was causing a strange double error responses (mix of JSON / plain text), e.g.:
```
could not enforce labels: parse expr error: 1:13: parse error: unexpected end of input inside braces
{"status":"error","errorType":"bad_data","error":"1:13: parse error: unexpected end of input inside braces"}
```
After some investigation, I realized we are actually continuing in the middleware chain even if the label enforcement fails, but this should not be the case. The provided fix ensures we return from the middleware chain once the enforcement fails.

Do not continue with a request if label enforcement fails

---

.circleci/config.yml
Dockerfile
Dockerfile.e2e-test

This PR updates the project to go1.18

Update golang to v1.18

---

README.md
api/logs/v1/http.go
jsonnet/lib/observatorium-api.libsonnet
main.go

Add support for log recording and alerting rules

---

main.go

Allow service to be used only for tracing

---

authentication/openshift.go

Add openshift auth gRPC middleware

---

api/metrics/legacy/http.go
api/metrics/v1/http.go
main.go
server/http_instrumentation.go
server/paths.go

There is a problem in the existing setup of the handlers where if a middleware causes the HTTP response to return early, the Prometheus metrics for the HTTP handlers never get to see the request/response.
This PR attempts to reorganise the structure in a backwards compatible way by moving the instrumentation middleware to the top of the handlers stack enabling us to count all response codes in case of failures (rate limiting, auth, etc).
There also appears to be an issue where some of the middlewares will have been called multiple times as they were appended in both `main.go` and the specific handlers. I have adjusted these so they will get called in their respective handler. 
`stripTenantPrefix` now moves to middleware called in each handler since we want the middlewares to receive the …

Metrics middleware reorg

---

main.go

This fixes the rules-raw handler instrumentation. Missed from #430 review.

Fix rules-raw handler instrumentation

---

api/logs/v1/labels_enforcer.go
api/logs/v1/labels_enforcer_test.go
logql/v2/ast.go

This PR introduce some optimization to the query authorization label matchers.
JIRA issue: [LOG-3480](https://issues.redhat.com/browse/LOG-3480)
cc @xperimental

Optimize query authorization

---

jsonnet/lib/observatorium-api.libsonnet

Follows on from https://github.com/observatorium/api/pull/556

Add am endpoint to jsonnet config

---

ratelimit/http.go

TODO: Add a flag later 
Account for slow networks

Increase rate limit request timeout to 2s

---

api/logs/v1/http.go

This PR adds support for Loki's volume and volume_range API

Add Loki Volume API

---

go.mod
go.sum

https://issues.redhat.com/browse/TRACING-4901

Bump gomarkdown indirect dependency

---

api/logs/v1/labels_enforcer.go
api/logs/v1/labels_enforcer_test.go

Fixes https://issues.redhat.com/browse/LOG-7421

fix(logs): use correct variable for netobserv code path
